#!/bin/sh

ssh \
-R $NAME.$SERVICE:$REMOTE_PORT:$CONTAINER:$HOST_PORT \
-p $SERVICE_PORT \
-o ServerAliveInterval=30 \
-o ServerAliveCountMax=3 \
-o StrictHostKeyChecking=no \
-o TCPKeepAlive=yes \
$SERVICE
